openapi: "3.0.0"
info:
  version: 1.0.0
  title: Meetup Clone API
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Identity:
      $ref: 'schemas/identity.yaml'
    User:
      $ref: 'schemas/user.yaml'
    Users:
      $ref: 'schemas/users.yaml'
    Group:
      $ref: 'schemas/group.yaml'
    Groups:
      $ref: 'schemas/groups.yaml'
    Event:
      $ref: 'schemas/event.yaml'
    Events:
      $ref: 'schemas/events.yaml'
    Rsvp:
      $ref: 'schemas/rsvp.yaml'
    Response:
      required:
        - response
      properties:
        response:
          type: string
paths:
  /auth:
    $ref: 'paths/auth.yaml'
  /users:
    $ref: 'paths/users.yaml'
  /user/{id}:
    $ref: 'paths/user_id.yaml'
  /user/{id}/picture:
    $ref: 'paths/user_id_picture.yaml'
  /confirm/{id}:
    $ref: 'paths/confirm.yaml'
  /groups:
    $ref: 'paths/groups.yaml'
  /group/{id}:
    $ref: 'paths/group_id.yaml'
  /group/{id}/members:
    $ref: 'paths/group_id_members.yaml'
  /group/{id}/member/{mid}:
    $ref: 'paths/group_id_member_mid.yaml'
  /group/{id}/events:
    $ref: 'paths/group_id_events.yaml'
  /group/{id}/event/{eid}:
    $ref: 'paths/group_id_event_eid.yaml'
  /group/{id}/event/{eid}/rsvp:
    $ref: 'paths/rsvp.yaml'
