openapi: "3.0.0"
info:
  version: 1.0.0
  title: Meetup Clone API
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /groups:
    get:
      summary: List all groups
      operationId: listGroups
      tags:
        - groups
      parameters:
        - name: location
          in: query
          required: false
          description: the location
          schema:
            type: string
        - name: radius
          in: query
          required: false
          default: 20km
          description: location radius
          schema:
            type: string
  /group/{id}:
    post:
      summary: Create new group
      operationId: createGroup
      parameters:
      - name: id
        in: path
        required: true
        description: group id
        schema:
          type: string
      tags:
        - groups
    put:
      summary: Update group
      operationId: updateGroup
    parameters:
      - name: id
        in: path
        required: true
        description: group id
        schema:
          type: string
      tags:
        - groups
    delete:
      summary: Delete group
      operationId: deleteGroup
      parameters:
      - name: id
        in: path
        required: true
        description: group id
        schema:
          type: string
      tags:
        - groups
    